# Generated by Django 4.1.3 on 2022-11-27 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_statustype_alter_task_date_finish_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusType',
            new_name='ToDoCategory',
        ),
    ]
