# Generated by Django 4.1.3 on 2022-11-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_rename_statustype_todocategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='todocategory',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='id_column',
            new_name='column_id',
        ),
        migrations.AlterModelTable(
            name='task',
            table='to_do_list_task',
        ),
        migrations.AlterModelTable(
            name='todocategory',
            table='to_do_list_todocategory',
        ),
    ]
