# Generated by Django 4.1.3 on 2022-12-28 17:18

from django.db import migrations, models
import to_do_list.models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0007_task_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=to_do_list.models.last_order_value, editable=False),
        ),
    ]
